### ISSUE TITLE
not enough 'y' data when running KS-mean test in topologyTest() function

### ISSUE THREAD

**Issue by PeggySze** [HectorRDB/condiments#5] opened 2021-07-23 02:40 UTC
Hello! Firstly, thanks for develping such a good framework which allows the interpretation of differences between conditions at the trajectory. I have applied it to my own data but meet an error when running topologyTest(). Here is my data in singleCellExperiment format : https://mab.to/54UJvluRg
Here is my code and error information :
```
## Load dataset
germline_cells_scRNA.sce <- readRDS("integrated_germline_cells_scRNA_sce.rds")

## Trajectory Inference
germline_cells_slingshot <- slingshot(germline_cells_scRNA.sce, reducedDim = 'UMAP',
                  clusterLabels = colData(germline_cells_scRNA.sce)$rough_cell_type,
                  start.clus = "GSCs", end.clus="Late spermatids",approx_points = 100)

## topologyTest
set.seed(100)
topologyTest(SlingshotDataSet(germline_cells_slingshot), conditions=colData(germline_cells_scRNA.sce)$sample_type, methods = "KS_mean", threshs = .01,rep=50)

Running KS-mean test
Error in Ecume::ks_test(x = og_psts, w_x = og_ws, y = psts, w_y = ws,  : 
  not enough 'y' data
```
Could you pelease tell me how to solve this problem ? Thanks a lot !

**Comment by HectorRDB** [comment] 2021-07-23 09:40
Hi @PeggySze 
Thanks for the feedback and for providing the data.

Could you check that you have the latest version of both the Ecume package and condiments? This is an old bug that should be fixed now. Indeed, I cannot reproduce it on my computer. 
Best

**Comment by PeggySze** [comment] 2021-07-23 10:26
Here is the information of my current R session :
```
R version 4.1.0 (2021-05-18)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /public/home/shipy3/miniconda3/envs/condiments/lib/libopenblasp-r0.3.15.so

locale:
[1] C

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] tradeSeq_1.6.0              slingshot_2.0.0            
 [3] TrajectoryUtils_1.0.0       SingleCellExperiment_1.14.1
 [5] SummarizedExperiment_1.22.0 Biobase_2.52.0             
 [7] GenomicRanges_1.44.0        GenomeInfoDb_1.28.1        
 [9] IRanges_2.26.0              S4Vectors_0.30.0           
[11] BiocGenerics_0.38.0         MatrixGenerics_1.4.0       
[13] matrixStats_0.59.0          princurve_2.1.6            
[15] ggplot2_3.3.5               RColorBrewer_1.1-2         
[17] dplyr_1.0.7                 condiments_1.0.0           

loaded via a namespace (and not attached):
  [1] Rtsne_0.15                VGAM_1.1-5               
  [3] colorspace_2.0-2          deldir_0.2-10            
  [5] ellipsis_0.3.2            class_7.3-19             
  [7] XVector_0.32.0            proxy_0.4-26             
  [9] spatstat.data_2.1-0       ggrepel_0.9.1            
 [11] prodlim_2019.11.13        fansi_0.5.0              
 [13] lubridate_1.7.10          sparseMatrixStats_1.4.0  
 [15] codetools_0.2-18          splines_4.1.0            
 [17] docopt_0.7.1              polyclip_1.10-0          
 [19] pROC_1.17.0.1             caret_6.0-88             
 [21] cluster_2.1.2             kernlab_0.9-29           
 [23] pheatmap_1.0.12           spatstat.linnet_2.3-0    
 [25] spatstat.sparse_2.0-0     compiler_4.1.0           
 [27] Matrix_1.3-4              cli_3.0.1                
 [29] limma_3.48.1              tools_4.1.0              
 [31] igraph_1.2.6              gtable_0.3.0             
 [33] glue_1.4.2                GenomeInfoDbData_1.2.6   
 [35] RANN_2.6.1                reshape2_1.4.4           
 [37] Rcpp_1.0.7                spatstat_2.2-0           
 [39] slam_0.1-48               DDRTree_0.1.5            
 [41] vctrs_0.3.8               nlme_3.1-152             
 [43] DelayedMatrixStats_1.14.0 iterators_1.0.13         
 [45] timeDate_3043.102         gower_0.2.2              
 [47] stringr_1.4.0             Ecume_0.9.1              
 [49] lifecycle_1.0.0           irlba_2.3.3              
 [51] goftest_1.2-2             edgeR_3.34.0             
 [53] zlibbioc_1.38.0           MASS_7.3-54              
 [55] scales_1.1.1              ipred_0.9-11             
 [57] spatstat.core_2.3-0       spatstat.utils_2.2-0     
 [59] monocle_2.20.0            gridExtra_2.3            
 [61] pbapply_1.4-3             rpart_4.1-15             
 [63] fastICA_1.2-2             stringi_1.7.3            
 [65] foreach_1.5.1             e1071_1.7-7              
 [67] densityClust_0.3          BiocParallel_1.26.1      
 [69] lava_1.6.9                rlang_0.4.11             
 [71] pkgconfig_2.0.3           bitops_1.0-7             
 [73] qlcMatrix_0.9.7           lattice_0.20-44          
 [75] purrr_0.3.4               tensor_1.5               
 [77] recipes_0.1.16            transport_0.12-2         
 [79] tidyselect_1.1.1          plyr_1.8.6               
 [81] magrittr_2.0.1            R6_2.5.0                 
 [83] generics_0.1.0            combinat_0.0-8           
 [85] DelayedArray_0.18.0       pillar_1.6.1             
 [87] withr_2.4.2               mgcv_1.8-36              
 [89] survival_3.2-11           abind_1.4-5              
 [91] RCurl_1.98-1.3            nnet_7.3-16              
 [93] tibble_3.1.2              crayon_1.4.1             
 [95] utf8_1.2.1                spatstat.geom_2.2-2      
 [97] viridis_0.6.1             locfit_1.5-9.4           
 [99] grid_4.1.0                data.table_1.14.0        
[101] FNN_1.1.3                 ModelMetrics_1.2.2.2     
[103] sparsesvd_0.2             HSMMSingleCell_1.12.0    
[105] munsell_0.5.0             viridisLite_0.4.0  
```
I think that both the Ecume package and condiments are the latest version.

**Comment by HectorRDB** [comment] 2021-07-23 11:24
Ok.
Please try to install the latest version of condiments from github
```
if(!requireNamespace("devtools", quietly = TRUE)) {
 install.packages("devtools") 
}
devtools::install_github("HectorRDB/condiments")
```

**Comment by HectorRDB** [comment] 2021-09-10 07:54
Closing after a month of inactivity. Feel free to re-open if the issue persists

**Closed by HectorRDB** 2021-09-10 07:54 UTC
